name: Build Windows Exe

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows
        run: flutter build windows --release

      - name: Create MSIX
        run: dart run msix:create

      - name: Compress Build Folder
        run: Compress-Archive -Path build\windows\x64\runner\Release\* -DestinationPath AlochiMonitoring-Windows.zip

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AlochiMonitoring-Windows
          path: AlochiMonitoring-Windows.zip

      - name: Upload MSIX Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AlochiMonitoring-MSIX
          path: build\windows\alochi-monitoring.msix

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "Latest Windows Version"
          body: "Alochi Monitoring dasturining eng so'nggi (MSIX paketli) Windows versiyasi."
          files: |
            AlochiMonitoring-Windows.zip
            build/windows/alochi-monitoring.msix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
